### ISSUE TITLE
Undefined method ip_address for nil

### ISSUE THREAD

**Issue by mgrigajtis** [nofxx/hooray#4]
hoo init ran ok, but hoo list bombs:

```
Matthews-MacBook-Pro:~ matthewgrigajtis$ hoo init

                             Hooray!
Creating ~/.hooray directory
Creating ~/.hooray/settings.yml
Creating ~/.hooray/devices.yml
Creating ~/.hooray/services.yml
Creating ~/.hooray/nmap-mac-prefixes
Matthews-MacBook-Pro:~ matthewgrigajtis$ hoo list

                             Hooray!
Listing devices * []
/Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/hooray-0.0.5/lib/hooray/seek.rb:71:in `my_lan_ip': undefined method `ip_address' for nil:NilClass (NoMethodError)
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/hooray-0.0.5/lib/hooray/seek.rb:75:in `local_mask'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/hooray-0.0.5/lib/hooray/seek.rb:12:in `initialize'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/hooray-0.0.5/lib/hooray/cli.rb:41:in `new'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/hooray-0.0.5/lib/hooray/cli.rb:41:in `list'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/gems/hooray-0.0.5/bin/hoo:9:in `<top (required)>'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/bin/hoo:23:in `load'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/bin/hoo:23:in `<main>'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/matthewgrigajtis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nofxx** [comment]
On mac it's 2 seconds slower, problem with macaddr lib.
But working, this one is fixed.
